//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NegociosElectronicosII.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Body HTML.
        /// </summary>
        internal static string BodyHTML {
            get {
                return ResourceManager.GetString("BodyHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es abierta.
        /// </summary>
        internal static string EsAbierta {
            get {
                return ResourceManager.GetString("EsAbierta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es cliente.
        /// </summary>
        internal static string EsCliente {
            get {
                return ResourceManager.GetString("EsCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de cierre.
        /// </summary>
        internal static string FechaDeCierre {
            get {
                return ResourceManager.GetString("FechaDeCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de creacion.
        /// </summary>
        internal static string FechaDeCreacion {
            get {
                return ResourceManager.GetString("FechaDeCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de inicio.
        /// </summary>
        internal static string FechaDelnicio {
            get {
                return ResourceManager.GetString("FechaDelnicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de registro.
        /// </summary>
        internal static string FechaDeRegistro {
            get {
                return ResourceManager.GetString("FechaDeRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de respuesta.
        /// </summary>
        internal static string FechaDeRespuesta {
            get {
                return ResourceManager.GetString("FechaDeRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitacora.
        /// </summary>
        internal static string NE_Bitacora {
            get {
                return ResourceManager.GetString("NE_Bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrusel.
        /// </summary>
        internal static string NE_Carrusel {
            get {
                return ResourceManager.GetString("NE_Carrusel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios del producto.
        /// </summary>
        internal static string NE_ComentarioProducto {
            get {
                return ResourceManager.GetString("NE_ComentarioProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuerpo del chat.
        /// </summary>
        internal static string NE_CuerpoChat {
            get {
                return ResourceManager.GetString("NE_CuerpoChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezado del chat.
        /// </summary>
        internal static string NE_EncabezadoChat {
            get {
                return ResourceManager.GetString("NE_EncabezadoChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuesta.
        /// </summary>
        internal static string NE_Encuesta {
            get {
                return ResourceManager.GetString("NE_Encuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preguntas frecuentes.
        /// </summary>
        internal static string NE_FAQS {
            get {
                return ResourceManager.GetString("NE_FAQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta.
        /// </summary>
        internal static string NE_Pregunta {
            get {
                return ResourceManager.GetString("NE_Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string NE_Producto {
            get {
                return ResourceManager.GetString("NE_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta.
        /// </summary>
        internal static string NE_RespuestPregunta {
            get {
                return ResourceManager.GetString("NE_RespuestPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Templates.
        /// </summary>
        internal static string NE_Templates {
            get {
                return ResourceManager.GetString("NE_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visitas.
        /// </summary>
        internal static string NE_Visitas {
            get {
                return ResourceManager.GetString("NE_Visitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del archivo.
        /// </summary>
        internal static string NombreDelArchivo {
            get {
                return ResourceManager.GetString("NombreDelArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio de compra.
        /// </summary>
        internal static string PrecioCompra {
            get {
                return ResourceManager.GetString("PrecioCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio de venta.
        /// </summary>
        internal static string PrecioVenta {
            get {
                return ResourceManager.GetString("PrecioVenta", resourceCulture);
            }
        }
    }
}
