//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENSES_Guests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENSES_Guests()
        {
            this.ENSES_RelGuestsHosting = new HashSet<ENSES_RelGuestsHosting>();
        }
    
        public int ID_Guests { get; set; }
        public string Diocese { get; set; }
        public string Coordinator { get; set; }
        public string PhoneNumber { get; set; }
        public int BusTotal { get; set; }
        public int YEAR { get; set; }
        public string Folio { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string CoordinatorEmail { get; set; }
        public Nullable<decimal> Ltn { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public int Men { get; set; }
        public int Women { get; set; }
        public int Both { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENSES_RelGuestsHosting> ENSES_RelGuestsHosting { get; set; }
    }
}
