//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENSES_HostingCoordinator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENSES_HostingCoordinator()
        {
            this.ENSES_RelGuestsHosting = new HashSet<ENSES_RelGuestsHosting>();
        }
    
        public int ID_HostingCoordinator { get; set; }
        public string HostingCoordinator { get; set; }
        public string Folio { get; set; }
        public string PhoneNumber { get; set; }
        public string CelphoneNumber { get; set; }
        public string Email { get; set; }
        public string ParishToWhichItBelongs { get; set; }
        public int Vehicles { get; set; }
        public int PeopleToHosting { get; set; }
        public string VehiclesType { get; set; }
        public int YEAR { get; set; }
        public Nullable<decimal> Ltn { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public int ID_Group { get; set; }
        public int Men { get; set; }
        public int Women { get; set; }
        public int Both { get; set; }
    
        public virtual ENSES_Group ENSES_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENSES_RelGuestsHosting> ENSES_RelGuestsHosting { get; set; }
    }
}
