//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENSES_Hosting
    {
        public int ID_Hosting { get; set; }
        public string Host { get; set; }
        public string Folio { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Celphone { get; set; }
        public string Email { get; set; }
        public string HostingPlace { get; set; }
        public string Street { get; set; }
        public int Number { get; set; }
        public string Suburb { get; set; }
        public string ParishToWhichItBelongs { get; set; }
        public int PeopleNumberAvaibleHosting { get; set; }
        public string DelieveringPlaceToGuests { get; set; }
        public int YEAR { get; set; }
    }
}
