//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENSES_RelGuestsHosting
    {
        public int ID_RelGuestsHosting { get; set; }
        public int ID_Guests { get; set; }
        public int ID_HostingCoordinator { get; set; }
        public string TagTable { get; set; }
        public Nullable<int> PeopleNumber { get; set; }
        public Nullable<int> BusTotal { get; set; }
        public Nullable<int> Men { get; set; }
        public Nullable<int> Women { get; set; }
    
        public virtual ENSES_Guests ENSES_Guests { get; set; }
        public virtual ENSES_HostingCoordinator ENSES_HostingCoordinator { get; set; }
    }
}
