//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_CuerpoChat
    {
        public int CuerpoChatId { get; set; }
        public int ChatId { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public string Mensaje { get; set; }
        public bool EsCliente { get; set; }
    
        public virtual NE_EncabezadoChat NE_EncabezadoChat { get; set; }
    }
}
