//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_Carrusel
    {
        public int CarruselId { get; set; }
        public int Posicion { get; set; }
        public string Texto { get; set; }
        public string Descripcion { get; set; }
        public string Ruta { get; set; }
        public string Extension { get; set; }
        public string NombreArchivo { get; set; }
        public bool Activo { get; set; }
    }
}
