//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_EncabezadoChat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NE_EncabezadoChat()
        {
            this.NE_CuerpoChat = new HashSet<NE_CuerpoChat>();
        }
    
        public int ChatId { get; set; }
        public string Alias { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaDeInicio { get; set; }
        public System.DateTime FechaDeCierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NE_CuerpoChat> NE_CuerpoChat { get; set; }
        public virtual NE_Usuario NE_Usuario { get; set; }
    }
}
