//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_EncabezadoChat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NE_EncabezadoChat()
        {
            this.NE_CuerpoChat = new HashSet<NE_CuerpoChat>();
        }
    
        public int ChatId { get; set; }
        public string Alias { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaDeInicio { get; set; }
        public Nullable<System.DateTime> FechaDeCierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NE_CuerpoChat> NE_CuerpoChat { get; set; }
        public virtual NE_Usuario NE_Usuario { get; set; }
    }
}
