//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_ProductoImagen
    {
        public int ProductoImagenId { get; set; }
        public string Ruta { get; set; }
        public string Nombre { get; set; }
        public string Extension { get; set; }
        public int ProductoId { get; set; }
    
        public virtual NE_Producto NE_Producto { get; set; }
    }
}
