//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_Producto
    {
        public int Id_Producto { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public int Stock { get; set; }
        public decimal Precio_Venta { get; set; }
        public decimal Precio_Compra { get; set; }
        public bool Activo { get; set; }
        public int Id_Category { get; set; }
    
        public virtual NE_Category NE_Category { get; set; }
    }
}
