//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_VentaDetalle
    {
        public int VentaDetalleId { get; set; }
        public int VentaId { get; set; }
        public Nullable<int> VehiculoId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual NE_Producto NE_Producto { get; set; }
        public virtual NE_Vehiculo NE_Vehiculo { get; set; }
        public virtual NE_Venta NE_Venta { get; set; }
    }
}
