//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_AciertosJornadas
    {
        public long AciertoJornadaId { get; set; }
        public int NoJornada { get; set; }
        public long ParticipanteId { get; set; }
        public long Id_Quiniela { get; set; }
        public int NoAciertos { get; set; }
        public int NoErrores { get; set; }
    
        public virtual Q_Participante Q_Participante { get; set; }
        public virtual Q_Quiniela Q_Quiniela { get; set; }
    }
}
