//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Pronostico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Q_Pronostico()
        {
            this.Q_Resultados = new HashSet<Q_Resultados>();
        }
    
        public long PronosticoId { get; set; }
        public int NoJornada { get; set; }
        public Nullable<int> NoPartido { get; set; }
        public string Description { get; set; }
        public string Resultado { get; set; }
        public long Id_Quiniela { get; set; }
    
        public virtual Q_Quiniela Q_Quiniela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Q_Resultados> Q_Resultados { get; set; }
    }
}
