//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Quiniela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Q_Quiniela()
        {
            this.Q_AciertosJornadas = new HashSet<Q_AciertosJornadas>();
            this.Q_Pronostico = new HashSet<Q_Pronostico>();
            this.Q_RelQuinielaParticipante = new HashSet<Q_RelQuinielaParticipante>();
            this.Q_Total = new HashSet<Q_Total>();
        }
    
        public long Id_Quiniela { get; set; }
        public string NombreDeQuiniela { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public System.DateTime FechaDePago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Q_AciertosJornadas> Q_AciertosJornadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Q_Pronostico> Q_Pronostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Q_RelQuinielaParticipante> Q_RelQuinielaParticipante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Q_Total> Q_Total { get; set; }
    }
}
