//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Resultados
    {
        public long IdResultado { get; set; }
        public long IdPronostico { get; set; }
        public long IdParticipante { get; set; }
        public string Pronostico { get; set; }
        public long Id_Quiniela { get; set; }
    
        public virtual Q_Participante Q_Participante { get; set; }
        public virtual Q_Pronostico Q_Pronostico { get; set; }
    }
}
