//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Client()
        {
            this.Tb_SalesHeader = new HashSet<Tb_SalesHeader>();
            this.Tb_SalesHeader1 = new HashSet<Tb_SalesHeader>();
        }
    
        public long ClientId { get; set; }
        public string Names { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long ZipCodeId { get; set; }
        public string Email { get; set; }
        public string CellPhone { get; set; }
        public string Phone { get; set; }
        public string Street { get; set; }
        public string IntNumber { get; set; }
        public Nullable<int> ExtNumber { get; set; }
        public Nullable<long> MunicipalityId { get; set; }
        public Nullable<long> LocalityId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> SuburbId { get; set; }
        public bool IsReference { get; set; }
        public string ReferenceType { get; set; }
    
        public virtual Tb_Locality Tb_Locality { get; set; }
        public virtual Tb_Municipality Tb_Municipality { get; set; }
        public virtual Tb_State Tb_State { get; set; }
        public virtual Tb_Suburb Tb_Suburb { get; set; }
        public virtual Tb_ZipCode Tb_ZipCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SalesHeader> Tb_SalesHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SalesHeader> Tb_SalesHeader1 { get; set; }
    }
}
