//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_FilesPaymentProfits
    {
        public long FileId { get; set; }
        public byte[] File { get; set; }
        public string Key { get; set; }
        public string Extension { get; set; }
        public long PaymentsProfitsId { get; set; }
        public string FileName { get; set; }
    
        public virtual Tb_PaymentProfits Tb_PaymentProfits { get; set; }
    }
}
