//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_HitchSalesReport
    {
        public long IDHitchSalesReport { get; set; }
        public long SalesReportId { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public decimal Total { get; set; }
        public int TypeHSRID { get; set; }
    
        public virtual Tb_SalesReport Tb_SalesReport { get; set; }
        public virtual Tb_TypeHSR Tb_TypeHSR { get; set; }
    }
}
