//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Inventory
    {
        public long StockId { get; set; }
        public long ProductId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsClosed { get; set; }
        public int GroupId { get; set; }
    
        public virtual Tb_Group Tb_Group { get; set; }
        public virtual Tb_Product Tb_Product { get; set; }
    }
}
