//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_OutputNotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_OutputNotes()
        {
            this.Tb_OutputNotesDetail = new HashSet<Tb_OutputNotesDetail>();
            this.Tb_Rel_WHC_OCN = new HashSet<Tb_Rel_WHC_OCN>();
        }
    
        public long OutputNoteCardId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string Folio { get; set; }
        public string Concept { get; set; }
        public long DelieverId { get; set; }
        public long ChargerId { get; set; }
        public decimal Total { get; set; }
        public long StatusDocumentId { get; set; }
        public long MerchandiseReceiverId { get; set; }
        public byte[] SignMerchandiseReceiver { get; set; }
        public long AuthorizerId { get; set; }
        public byte[] SignAuthorizer { get; set; }
        public long DelieverUserId { get; set; }
        public byte[] SignDeliever { get; set; }
        public long OtherSignerId { get; set; }
        public byte[] OtherSign { get; set; }
    
        public virtual Tb_Group Tb_Group { get; set; }
        public virtual Tb_StatusDocumentId Tb_StatusDocumentId { get; set; }
        public virtual Tb_User Tb_User { get; set; }
        public virtual Tb_User Tb_User1 { get; set; }
        public virtual Tb_User Tb_User2 { get; set; }
        public virtual Tb_User Tb_User3 { get; set; }
        public virtual Tb_User Tb_User4 { get; set; }
        public virtual Tb_User Tb_User5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_OutputNotesDetail> Tb_OutputNotesDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Rel_WHC_OCN> Tb_Rel_WHC_OCN { get; set; }
    }
}
