//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_OutputNotesDetail
    {
        public long OutputNoteDetailId { get; set; }
        public int Quantity { get; set; }
        public long ProductId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<long> OutputNoteId { get; set; }
    
        public virtual Tb_OutputNotes Tb_OutputNotes { get; set; }
        public virtual Tb_Product Tb_Product { get; set; }
    }
}
