//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Product()
        {
            this.Tb_Inventory = new HashSet<Tb_Inventory>();
            this.Tb_InventoryPaymentProfit = new HashSet<Tb_InventoryPaymentProfit>();
            this.Tb_OutputNotesDetail = new HashSet<Tb_OutputNotesDetail>();
            this.Tb_RelProdWHControl = new HashSet<Tb_RelProdWHControl>();
            this.Tb_SalesDetail = new HashSet<Tb_SalesDetail>();
            this.Tb_TransportGuideDetail = new HashSet<Tb_TransportGuideDetail>();
            this.Tb_WarehouseControlDetail = new HashSet<Tb_WarehouseControlDetail>();
        }
    
        public long ProductId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public decimal PurchisePrice { get; set; }
        public long UnitMeasureId { get; set; }
        public long ProductTypeId { get; set; }
        public decimal SalesPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Inventory> Tb_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_InventoryPaymentProfit> Tb_InventoryPaymentProfit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_OutputNotesDetail> Tb_OutputNotesDetail { get; set; }
        public virtual Tb_ProductType Tb_ProductType { get; set; }
        public virtual Tb_UnitMeasure Tb_UnitMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_RelProdWHControl> Tb_RelProdWHControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SalesDetail> Tb_SalesDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_TransportGuideDetail> Tb_TransportGuideDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_WarehouseControlDetail> Tb_WarehouseControlDetail { get; set; }
    }
}
