//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_paymentsProfitsRows
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_paymentsProfitsRows()
        {
            this.Tb_PaymentProfitProduct = new HashSet<Tb_PaymentProfitProduct>();
        }
    
        public long ID { get; set; }
        public long PaymentProfitsID { get; set; }
        public int NumRow { get; set; }
        public int PayedCards { get; set; }
        public int HitchedCards { get; set; }
        public int NoHitchedCards { get; set; }
        public int CanceledCards { get; set; }
        public int TotalCards { get; set; }
        public decimal PayedCardsAmount { get; set; }
        public decimal HitchedCardsAmount { get; set; }
        public decimal NoHitchedCardsAmount { get; set; }
        public decimal CanceledCardsAmount { get; set; }
        public decimal TotalCardsAmount { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_PaymentProfitProduct> Tb_PaymentProfitProduct { get; set; }
        public virtual Tb_PaymentProfits Tb_PaymentProfits { get; set; }
    }
}
