//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_RelWHC_TransGuide
    {
        public long RelWHC_TransGuideId { get; set; }
        public long TransportGuideId { get; set; }
        public long WarehouseCardId { get; set; }
    
        public virtual Tb_TransportGuide Tb_TransportGuide { get; set; }
        public virtual Tb_WarehouseControl Tb_WarehouseControl { get; set; }
    }
}
