//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Rel_WHC_OCN
    {
        public long Rel_WHC_OCN_Id { get; set; }
        public long WarehouseCardId { get; set; }
        public long OutputNotesCardId { get; set; }
    
        public virtual Tb_OutputNotes Tb_OutputNotes { get; set; }
        public virtual Tb_WarehouseControl Tb_WarehouseControl { get; set; }
    }
}
