//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_RouteDetail
    {
        public long RouteDetailId { get; set; }
        public long RouteId { get; set; }
        public int PointNumber { get; set; }
        public string Coordenates { get; set; }
        public string Address { get; set; }
        public bool Active { get; set; }
    
        public virtual Tb_Route Tb_Route { get; set; }
    }
}
