//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Rel_SR_Sales
    {
        public long ID { get; set; }
        public long SalesReportID { get; set; }
        public long SalesId { get; set; }
    
        public virtual Tb_SalesHeader Tb_SalesHeader { get; set; }
    }
}
