//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SalesReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_SalesReport()
        {
            this.Tb_FilesSalesReport = new HashSet<Tb_FilesSalesReport>();
            this.Tb_HitchSalesReport = new HashSet<Tb_HitchSalesReport>();
            this.Tb_SalesReportDetail = new HashSet<Tb_SalesReportDetail>();
        }
    
        public long SalesReportId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int GroupId { get; set; }
        public string Comments { get; set; }
        public decimal BoxSafe { get; set; }
        public decimal Subtotal { get; set; }
        public bool IsDeliever { get; set; }
        public decimal Subtotal2 { get; set; }
        public decimal DriverExpense { get; set; }
        public decimal CommissionTotal { get; set; }
        public decimal Oil { get; set; }
        public decimal Stepsways { get; set; }
        public decimal Rent { get; set; }
        public decimal Toolman { get; set; }
        public decimal Anothers { get; set; }
        public decimal Expense { get; set; }
        public Nullable<int> Mileage { get; set; }
        public string Enrollment { get; set; }
        public Nullable<decimal> ComissionPct { get; set; }
        public Nullable<decimal> ComissionSales { get; set; }
        public Nullable<bool> IsDiffToPay { get; set; }
        public Nullable<decimal> AmountTotal { get; set; }
        public decimal IMSS { get; set; }
        public decimal INFONAVIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_FilesSalesReport> Tb_FilesSalesReport { get; set; }
        public virtual Tb_Group Tb_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_HitchSalesReport> Tb_HitchSalesReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SalesReportDetail> Tb_SalesReportDetail { get; set; }
    }
}
