//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SalesPayment
    {
        public long SalesPaymentId { get; set; }
        public long SalesId { get; set; }
        public long SellerId { get; set; }
        public bool IsHitch { get; set; }
        public decimal Amount { get; set; }
        public string PaymentFolio { get; set; }
        public byte[] CheckerSign { get; set; }
        public long SignerId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int RowID { get; set; }
    
        public virtual Tb_SalesHeader Tb_SalesHeader { get; set; }
        public virtual Tb_User Tb_User { get; set; }
        public virtual Tb_User Tb_User1 { get; set; }
    }
}
