//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SalesHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_SalesHeader()
        {
            this.Tb_Rel_PP_Sales = new HashSet<Tb_Rel_PP_Sales>();
            this.Tb_Rel_SR_Sales = new HashSet<Tb_Rel_SR_Sales>();
            this.Tb_SalesDetail = new HashSet<Tb_SalesDetail>();
            this.Tb_SalesPayment = new HashSet<Tb_SalesPayment>();
        }
    
        public long SalesId { get; set; }
        public System.DateTime SalesDate { get; set; }
        public string Folio { get; set; }
        public long SellerId { get; set; }
        public decimal AmountTotal { get; set; }
        public System.DateTime FirstPaymentDate { get; set; }
        public System.DateTime LastPaymentDate { get; set; }
        public long ClientId { get; set; }
        public byte[] SignClient { get; set; }
        public long ReferenceId { get; set; }
        public string Reference { get; set; }
        public long StatusId { get; set; }
    
        public virtual Tb_Client Tb_Client { get; set; }
        public virtual Tb_Client Tb_Client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Rel_PP_Sales> Tb_Rel_PP_Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Rel_SR_Sales> Tb_Rel_SR_Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SalesDetail> Tb_SalesDetail { get; set; }
        public virtual Tb_StatusCard Tb_StatusCard { get; set; }
        public virtual Tb_User Tb_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SalesPayment> Tb_SalesPayment { get; set; }
    }
}
