//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SalesReportDetail
    {
        public long SalesReportDetailID { get; set; }
        public int AxisX { get; set; }
        public int AxisY { get; set; }
        public string Value { get; set; }
        public long SalesReportID { get; set; }
    
        public virtual Tb_SalesReport Tb_SalesReport { get; set; }
    }
}
