//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_TndPayments
    {
        public int ID_Payments { get; set; }
        public decimal Amount { get; set; }
        public int ID_RelUsuarioTanda { get; set; }
    
        public virtual Tb_TndRelUsuariosTanda Tb_TndRelUsuariosTanda { get; set; }
    }
}
