//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_TndTanda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_TndTanda()
        {
            this.Tb_TndRelUsuariosTanda = new HashSet<Tb_TndRelUsuariosTanda>();
        }
    
        public int ID_Tanda { get; set; }
        public string Descripcion { get; set; }
        public int Semanas { get; set; }
        public System.DateTime Inicio { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
        public int ID_StatusTanda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_TndRelUsuariosTanda> Tb_TndRelUsuariosTanda { get; set; }
        public virtual Tb_TndStatusTanda Tb_TndStatusTanda { get; set; }
    }
}
