//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_TndUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_TndUsuarios()
        {
            this.Tb_TndOthersPayments = new HashSet<Tb_TndOthersPayments>();
            this.Tb_TndOthersProds = new HashSet<Tb_TndOthersProds>();
            this.Tb_TndRelUsuariosTanda = new HashSet<Tb_TndRelUsuariosTanda>();
        }
    
        public int ID_Usuario { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public int ID_Rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_TndOthersPayments> Tb_TndOthersPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_TndOthersProds> Tb_TndOthersProds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_TndRelUsuariosTanda> Tb_TndRelUsuariosTanda { get; set; }
        public virtual Tb_TndRol Tb_TndRol { get; set; }
    }
}
