//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_TndOthersPayments
    {
        public int ID_Payments { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime RecordDate { get; set; }
        public int ID_Usuario { get; set; }
    
        public virtual Tb_TndUsuarios Tb_TndUsuarios { get; set; }
    }
}
