//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_TndProducto
    {
        public int ID_Producto { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public string Talla { get; set; }
        public string Producto { get; set; }
        public int ID_RelTandaUsuario { get; set; }
        public string ID_ProdDesc { get; set; }
        public decimal MontoReal { get; set; }
    
        public virtual Tb_TndRelUsuariosTanda Tb_TndRelUsuariosTanda { get; set; }
    }
}
