//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_UserLog
    {
        public long UserLogId { get; set; }
        public long UserId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string Geolocalitation { get; set; }
    
        public virtual Tb_User Tb_User { get; set; }
    }
}
