//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_User()
        {
            this.Tb_OutputNotes = new HashSet<Tb_OutputNotes>();
            this.Tb_OutputNotes1 = new HashSet<Tb_OutputNotes>();
            this.Tb_OutputNotes2 = new HashSet<Tb_OutputNotes>();
            this.Tb_OutputNotes3 = new HashSet<Tb_OutputNotes>();
            this.Tb_OutputNotes4 = new HashSet<Tb_OutputNotes>();
            this.Tb_OutputNotes5 = new HashSet<Tb_OutputNotes>();
            this.Tb_PaymentProfits = new HashSet<Tb_PaymentProfits>();
            this.Tb_SalesHeader = new HashSet<Tb_SalesHeader>();
            this.Tb_SalesPayment = new HashSet<Tb_SalesPayment>();
            this.Tb_SalesPayment1 = new HashSet<Tb_SalesPayment>();
            this.Tb_UserLog = new HashSet<Tb_UserLog>();
        }
    
        public long UserId { get; set; }
        public string Names { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int GroupId { get; set; }
        public bool Active { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public string Password { get; set; }
    
        public virtual Tb_Group Tb_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_OutputNotes> Tb_OutputNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_OutputNotes> Tb_OutputNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_OutputNotes> Tb_OutputNotes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_OutputNotes> Tb_OutputNotes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_OutputNotes> Tb_OutputNotes4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_OutputNotes> Tb_OutputNotes5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_PaymentProfits> Tb_PaymentProfits { get; set; }
        public virtual Tb_Profile Tb_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SalesHeader> Tb_SalesHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SalesPayment> Tb_SalesPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SalesPayment> Tb_SalesPayment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_UserLog> Tb_UserLog { get; set; }
    }
}
