//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_WarehouseControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_WarehouseControl()
        {
            this.Tb_Rel_WHC_OCN = new HashSet<Tb_Rel_WHC_OCN>();
            this.Tb_RelProdWHControl = new HashSet<Tb_RelProdWHControl>();
            this.Tb_RelWHC_TransGuide = new HashSet<Tb_RelWHC_TransGuide>();
            this.Tb_WarehouseControlDetail = new HashSet<Tb_WarehouseControlDetail>();
        }
    
        public long WarehouseCardId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string Folio { get; set; }
        public int WeekendNumber { get; set; }
        public int MonthNumber { get; set; }
        public int Year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Rel_WHC_OCN> Tb_Rel_WHC_OCN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_RelProdWHControl> Tb_RelProdWHControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_RelWHC_TransGuide> Tb_RelWHC_TransGuide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_WarehouseControlDetail> Tb_WarehouseControlDetail { get; set; }
    }
}
