//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Body
    {
        public int ID_Body { get; set; }
        public int ID_Header { get; set; }
        public int ID_Status { get; set; }
        public int ID_Activity { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int DayOfWeek { get; set; }
    
        public virtual TE_Activity TE_Activity { get; set; }
        public virtual TE_Header TE_Header { get; set; }
        public virtual TE_Status TE_Status { get; set; }
    }
}
