//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TE_Header()
        {
            this.TE_Body = new HashSet<TE_Body>();
        }
    
        public int ID_Header { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FromDate { get; set; }
        public int Week { get; set; }
        public string Tag { get; set; }
        public int ID_Board { get; set; }
    
        public virtual TE_Board TE_Board { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_Body> TE_Body { get; set; }
    }
}
