//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_RelActivityBoard
    {
        public int ID_RelActivityBoard { get; set; }
        public int ID_Board { get; set; }
        public int ID_Activity { get; set; }
    
        public virtual TE_Activity TE_Activity { get; set; }
        public virtual TE_Board TE_Board { get; set; }
    }
}
